id: I623970E0
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-19T14:36:02.479799'
last_modified: '2022-06-19T14:36:02.479809'
parser: null
source_metadata:
  title: Hagiography of Sa chen Kun dga snying po (1092-1158); Lamdre Lobshe, vol.
    ka, title no. 3, from the chronological biographies of the Lamdre lineage masters
  author: rje btsun grags pa rgyal mtshan/
  description: 'Digital version 2.0 {Wylie}; WYLIE COPY of master xml (completed:
    2013-08-16); converted from external file, unrevised, no thematic TEI markup'
  file_info:
  - 'Language: Wylie'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:Sakya Research Centre (src)
  - Text input:rdzong sar khams bye'i lnga rig slob gling / sde dge rdzong sar/ (dzkj)
  - Editorial process:Mathias Fermer (mf), Kunga Dorje (kun)
  - TEI Encoding:Sakya Research Centre
  - TEI Markup:-
  - Revisions/Corrections:-
  text_witnesses: https://sakyaresearch.org/sources/180
  bases:
    be17:
      title: Hagiography of Sa chen Kun dga snying po (1092-1158); Lamdre Lobshe,
        vol. ka, title no. 3, from the chronological biographies of the Lamdre lineage
        masters
      order: 1
      base_file: be17.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
